django_tweet_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('tweet_app.urls', 'tweet_app'), namespace='tweet_app')),
    path('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
]

tweet_app/urls.py
from django.urls import path
from . import views

app_name = 'tweet_app'

urlpatterns = [
    path('', views.list_tweets, name='list_tweets'),
    path('create/', views.create_tweet, name='create_tweet'), 
    path('create_tweet_by_form/', views.createTweetByForm, name='create_tweet_by_form'), 
    path('create_tweet_by_model_form/', views.createTweetByModelForm, name='create_tweet_by_model_form'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_tweet/<int:tweet_id>/', views.delete_tweet, name='delete_tweet'),
]

tweet_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.CharField(max_length=320)

    def __str__(self):
        return f"{self.username}: {self.text}"

tweet_app/forms.py
from django import forms
from django.forms import ModelForm
from tweet_app.models import Tweet

class CreateTweetForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    tweet = forms.CharField(label='Text', max_length=320, widget=forms.Textarea(attrs={'rows': 5}))

class CreateTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ['username', 'text']

tweet_app/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from tweet_app.forms import CreateTweetForm, CreateTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

# Create your views here.

def list_tweets(request):
    tweets = models.Tweet.objects.all()
    tweets_dictionary = {'tweets': tweets}
    return render(request, 'tweet_app/list_tweets.html', context=tweets_dictionary)

@login_required(login_url='/login')
def create_tweet(request):
    if request.POST:
        tweet = request.POST["tweet"]
        models.Tweet.objects.create(username=request.user, text=tweet)
        return redirect(reverse('tweet_app:list_tweets'))
    else:
        return render(request, 'tweet_app/create_tweet.html', {})
    
def createTweetByForm(request):
    if request.method == 'POST':
        form = CreateTweetForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            tweet = form.cleaned_data['tweet']
            models.Tweet.objects.create(username=username, text=tweet)
            return redirect(reverse('tweet_app:list_tweets'))
        else:
            print("Form is not valid")
            return render(request, 'tweet_app/create_tweet_by_form.html', context={'form': form})
    else:
        form = CreateTweetForm()
        return render(request, 'tweet_app/create_tweet_by_form.html', context={'form': form})
    
def createTweetByModelForm(request):
    if request.method == 'POST':
        form = CreateTweetModelForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            tweet = form.cleaned_data['text']
            models.Tweet.objects.create(username=username, text=tweet)
            return redirect(reverse('tweet_app:list_tweets'))
        else:
            print("Form is not valid")
            return render(request, 'tweet_app/create_tweet_by_model_form.html', context={'form': form})
    else:
        form = CreateTweetModelForm()
        return render(request, 'tweet_app/create_tweet_by_model_form.html', context={'form': form})
    
@login_required
def delete_tweet(request, tweet_id):
    tweet = models.Tweet.objects.get(id=tweet_id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=tweet_id).delete()
        return redirect(reverse('tweet_app:list_tweets'))

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('auth:login')
    template_name = 'registration/signup.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'tweet_app/custom_form.css' %}" />
    <title>Tweet App</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tweet_app:list_tweets' %}" style="padding-left: 1.5rem; padding-right: 1.5rem;">
                <i class="fa-brands fa-twitter"></i>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'tweet_app:list_tweets' %}"><i class="fa-solid fa-house"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweet_app:create_tweet' %}"><i class="fa-solid fa-pencil"></i> Create Tweet</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweet_app:create_tweet_by_form' %}">Tweet by Form</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweet_app:create_tweet_by_model_form' %}">Tweet by Model
                            Form</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}"><i class="fa-solid fa-user"></i> Account</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>

tweet_app/templates/tweet_app/create_tweet.html
{% extends 'base.html' %}

{% block content %}

<h1>Create Tweet</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}
        <!-- <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input type="text" class="form-control" id="username" name="username">
        </div> -->
        <div class="mb-3">
            <label for="tweet" class="form-label">Text:</label>
            <input type="text" class="form-control" id="tweet" name="tweet" placeholder="What's happening?">
        </div>
        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-pen"></i> Send Tweet</button>
    </form>
</div>

{% endblock %}

tweet_app/templates/tweet_app/create_tweet_by_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Create Tweet by Form</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div class="mb-3">
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Tweet</button>
    </form>
</div>
{% endblock %}

tweet_app/templates/tweet_app/create_tweet_by_model_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Create Tweet by Model Form</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div class="mb-3">
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Tweet</button>
    </form>
</div>
{% endblock %}

tweet_app/templates/tweet_app/list_tweets.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>

<div class="container" style="width: 50%;">
        {% for tweet in tweets %}
            <div class="card" style="padding: 10px;  margin-top: 20px;">
                <div class="card-header">
                    <h5><i class="fa-solid fa-circle-user"></i> {{ tweet.username }}
                    {% if tweet.username == user %}
                    <a href="{% url 'tweet_app:delete_tweet' tweet_id=tweet.id %}" class="btn btn-danger" style="float: right; width: 5%; height: 1%;"><i class="fa-solid fa-trash"></i></a>
                    {% endif %}
                </h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ tweet.text }}</p>
                </div>
            </div>
        {% endfor %}
</div>

{% endblock %}